# Generated by Django 4.2.4 on 2023-09-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('registro_geral', models.IntegerField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_de_nascimento', models.CharField(max_length=10, unique=True)),
                ('número_de_registro', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(default='cor padrão', max_length=50)),
                ('ano', models.IntegerField()),
                ('imagem_do_veiculo', models.ImageField(blank=True, null=True, upload_to='carros/')),
                ('cnh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.cnh')),
            ],
        ),
    ]
